call code --install-extension andyyaldoo.vscode-json
call code --install-extension ban.spellright
call code --install-extension ChaunceyKiwi.json-tree-view
call code --install-extension CoenraadS.bracket-pair-colorizer
call code --install-extension dbaeumer.vscode-eslint
call code --install-extension eg2.tslint
call code --install-extension flowtype.flow-for-vscode
call code --install-extension Ionide.Ionide-fsharp
call code --install-extension k--kato.docomment
call code --install-extension mauve.terraform
call code --install-extension ms-mssql.mssql
call code --install-extension ms-python.python
call code --install-extension ms-vscode.cpptools
call code --install-extension ms-vscode.csharp
call code --install-extension naumovs.color-highlight
call code --install-extension oderwat.indent-rainbow
call code --install-extension Orta.vscode-jest
call code --install-extension sdras.night-owl
call code --install-extension Unity.unity-debug
call code --install-extension vscodevim.vim
call code --install-extension vsmobile.vscode-react-native
call code --install-extension wayou.vscode-todo-highlight
